print ("wat voor soort dag is het")
woord1 = input ()
print("in welke stad")
stad1 = input()
print ("wat is je naam")
naam1 = input()
print ("wat zoek je")
woord2 = input()
print ("wie zag je")
woord3 = input()
print ("wat zag je")
woord4 = input()
print ("waar kwam je aan")
woord5 = input()
print ("verzin zelf iets")
woord_zin_7 = input()

print ("Het was een " + woord1 + " dag in "+ stad1 +".") 
print (naam1 + " liep door de straten, op zoek naar een "+woord2+ ".")
print ("Plotseling zag " + naam1 +" een "+ woord3 +" die een "+ woord4 + " verkocht.")
print (naam1 + " besloot om het te kopen en liep verder.")
print ("Toen "+ naam1 + " bij een "+ woord5 +" kwam, zag hij een groep mensen die "+ woord_zin_7 +".")
print (naam1+ " besloot om mee te doen en had de tijd van zijn/haar leven.")
