naam_1 = input("wat is je naam? ")
woord_1 = input("wat voor soort dag is het? ")
stad_1 = input("welke stad? ")
woord_2 = input("waar was je naar opzoek? ")
woord_3 = input("man of vrouw? ")
woord_4 = input("wat verkocht die persoon? ")
woord_5 = input("waar kwam je aan? ")
woord_zin_7 = input ("wat deed die groep mensen? ")

print(f"Het was een {woord_1} dag in {stad_1}.")
print(f"{naam_1} liep door de straten, op zoek naar een {woord_2}.")
print(f"Plotseling zag {naam_1} een {woord_3} die een {woord_4} verkocht.")
print(f"{naam_1} besloot om het te kopen en liep verder.")
print(f"Toen {naam_1} bij een {woord_5} kwam, zag hij/zij een groep mensen die {woord_zin_7}.")
print(f"{naam_1} besloot om mee te doen en had de tijd van zijn/haar leven.")